/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Url-encoded body with `style: deepObject` encoding
 * OpenAPI spec version: 1.0.0
 */
import type { PostAccountsNestedBodyAttributes } from './postAccountsNestedBodyAttributes';
import type { PostAccountsNestedBodyFreeform } from './postAccountsNestedBodyFreeform';
import type { PostAccountsNestedBodyLabels } from './postAccountsNestedBodyLabels';
import type { PostAccountsNestedBodyMetadata } from './postAccountsNestedBodyMetadata';
import type { PostAccountsNestedBodyUntouched } from './postAccountsNestedBodyUntouched';
import type { PostAccountsNestedBodyWarehouses } from './postAccountsNestedBodyWarehouses';

export type PostAccountsNestedBody = {
  name: string;
  metadata: PostAccountsNestedBodyMetadata;
  attributes?: PostAccountsNestedBodyAttributes;
  labels?: PostAccountsNestedBodyLabels;
  warehouses?: PostAccountsNestedBodyWarehouses;
  freeform?: PostAccountsNestedBodyFreeform;
  codes?: string[];
  untouched?: PostAccountsNestedBodyUntouched;
};
