/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Url-encoded body with `style: deepObject` encoding
 * OpenAPI spec version: 1.0.0
 */

export type PostAccountsNestedBodyUntouched = {
  foo?: string;
};
