/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Url-encoded body with `style: deepObject` encoding
 * OpenAPI spec version: 1.0.0
 */
import type { PostAccountsNestedBodyMetadataLinesItem } from './postAccountsNestedBodyMetadataLinesItem';
import type { PostAccountsNestedBodyMetadataShipping } from './postAccountsNestedBodyMetadataShipping';

export type PostAccountsNestedBodyMetadata = {
  order_id: string;
  priority?: number;
  tags?: string[];
  shipping?: PostAccountsNestedBodyMetadataShipping;
  lines?: PostAccountsNestedBodyMetadataLinesItem[];
  note?: string | null;
  retries?: number | null;
  matrix?: string[][];
};
