/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * const-with-enum
 * A property that carries both `enum` and `const` (as FastAPI / Pydantic v2
 * emit for a `Literal[...]` field) must generate the single const literal and
 * must not crash `getTypeConstEnum` with a non-string value.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Thing } from './model';

export const getThing = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Thing>> => {
  return axios.get(`/thing`, options);
};

export type GetThingResult = AxiosResponse<Thing>;
