/**
 * Generated by orval 🍺
 * Do not edit manually.
 * parameter-ref-schema-ref
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  GetInlineParamParams,
  GetReferencedParamParams,
  Kind,
} from './model';

export const getReferencedParam = (
  kind: Kind,
  params?: GetReferencedParamParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.get(`/referenced/${kind}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getInlineParam = (
  kind: Kind,
  params?: GetInlineParamParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.get(`/inline/${kind}`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export type GetReferencedParamResult = AxiosResponse<void>;
export type GetInlineParamResult = AxiosResponse<void>;
