/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/vue-query';
import type {
  DataTag,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query';

import { computed, toValue, unref } from 'vue';
import type { MaybeRefOrGetter } from 'vue';

import type {
  CreatePetsBody,
  CreatePetsParams,
  Error,
  ListPetsParams,
  Pet,
  PetWithTag,
  Pets,
} from './model';

import { useCustomInstance } from '../../../mutators/use-custom-instance-vue';
/**
 * @summary List all pets
 */
export const useListPetsHook = () => {
  const listPets = useCustomInstance<Pets>();

  return (
    params: MaybeRefOrGetter<ListPetsParams>,
    version: MaybeRefOrGetter<number> = 1,
    signal?: AbortSignal,
  ) => {
    params = toValue(params);
    version = toValue(version);

    return listPets({
      url: `/v${version}/pets`,
      method: 'GET',
      params,
      signal,
    });
  };
};

export const getListPetsInfiniteQueryKey = (
  params?: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return [
    'infinite',
    'v',
    version,
    'pets',
    ...(params ? [params] : []),
  ] as const;
};

export const getListPetsQueryKey = (
  params?: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'pets', ...(params ? [params] : [])] as const;
};

export const useListPetsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
        TError,
        TData,
        QueryKey,
        ListPetsParams['limit']
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getListPetsInfiniteQueryKey(params, version);

  const listPets = useListPetsHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
    QueryKey,
    ListPetsParams['limit']
  > = ({ signal, pageParam }) =>
    listPets(
      { ...toValue(params), limit: pageParam ?? toValue(params)?.['limit'] },
      version,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
    TError,
    TData,
    QueryKey,
    ListPetsParams['limit']
  >;
};

export type ListPetsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>
>;
export type ListPetsInfiniteQueryError = Error;

/**
 * @summary List all pets
 */

export function useListPetsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
        TError,
        TData,
        QueryKey,
        ListPetsParams['limit']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useListPetsInfiniteQueryOptions(
    params,
    version,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const useListPetsQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getListPetsQueryKey(params, version);

  const listPets = useListPetsHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>
  > = ({ signal }) => listPets(params, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
    TError,
    TData
  >;
};

export type ListPetsQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>
>;
export type ListPetsQueryError = Error;

/**
 * @summary List all pets
 */

export function useListPets<
  TData = Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListPetsHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useListPetsQueryOptions(params, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Create a pet
 */
export const useCreatePetsHook = () => {
  const createPets = useCustomInstance<Pet>();

  return (
    createPetsBody: MaybeRefOrGetter<CreatePetsBody>,
    params: MaybeRefOrGetter<CreatePetsParams>,
    version: MaybeRefOrGetter<number> = 1,
    signal?: AbortSignal,
  ) => {
    createPetsBody = toValue(createPetsBody);
    params = toValue(params);
    version = toValue(version);

    return createPets({
      url: `/v${version}/pets`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPetsBody,
      params,
      signal,
    });
  };
};

export const getCreatePetsQueryKey = (
  createPetsBody?: MaybeRefOrGetter<CreatePetsBody>,
  params?: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return [
    'POST',
    'v',
    version,
    'pets',
    ...(params ? [params] : []),
    createPetsBody,
  ] as const;
};

export const useCreatePetsQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>,
  TError = Error,
>(
  createPetsBody: MaybeRefOrGetter<CreatePetsBody>,
  params: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getCreatePetsQueryKey(createPetsBody, params, version);

  const createPets = useCreatePetsHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>
  > = ({ signal }) => createPets(createPetsBody, params, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>,
    TError,
    TData
  >;
};

export type CreatePetsQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>
>;
export type CreatePetsQueryError = Error;

/**
 * @summary Create a pet
 */

export function useCreatePets<
  TData = Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>,
  TError = Error,
>(
  createPetsBody: MaybeRefOrGetter<CreatePetsBody>,
  params: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useCreatePetsHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useCreatePetsQueryOptions(
    createPetsBody,
    params,
    version,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Info for a specific pet
 */
export const useShowPetByIdHook = () => {
  const showPetById = useCustomInstance<Pet>();

  return (
    petId: MaybeRefOrGetter<string>,
    version: MaybeRefOrGetter<number> = 1,
    signal?: AbortSignal,
  ) => {
    petId = toValue(petId);
    version = toValue(version);

    return showPetById({
      url: `/v${version}/pets/${petId}`,
      method: 'GET',
      signal,
    });
  };
};

export const getShowPetByIdQueryKey = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'pets', petId] as const;
};

export const useShowPetByIdQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getShowPetByIdQueryKey(petId, version);

  const showPetById = useShowPetByIdHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>
  > = ({ signal }) => showPetById(petId, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () =>
        toValue(version) !== null &&
        toValue(version) !== undefined &&
        toValue(petId) !== null &&
        toValue(petId) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>,
    TError,
    TData
  >;
};

export type ShowPetByIdQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>
>;
export type ShowPetByIdQueryError = Error;

/**
 * @summary Info for a specific pet
 */

export function useShowPetById<
  TData = Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useShowPetByIdHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useShowPetByIdQueryOptions(petId, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Deletes a specific pet
 */
export const useDeletePetByIdHook = () => {
  const deletePetById = useCustomInstance<void>();

  return (
    petId: MaybeRefOrGetter<string>,
    version: MaybeRefOrGetter<number> = 1,
    signal?: AbortSignal,
  ) => {
    petId = toValue(petId);
    version = toValue(version);

    return deletePetById({
      url: `/v${version}/pets/${petId}`,
      method: 'DELETE',
      signal,
    });
  };
};

export const getDeletePetByIdQueryKey = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['DELETE', 'v', version, 'pets', petId] as const;
};

export const useDeletePetByIdQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getDeletePetByIdQueryKey(petId, version);

  const deletePetById = useDeletePetByIdHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>
  > = ({ signal }) => deletePetById(petId, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () =>
        toValue(version) !== null &&
        toValue(version) !== undefined &&
        toValue(petId) !== null &&
        toValue(petId) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>,
    TError,
    TData
  >;
};

export type DeletePetByIdQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>
>;
export type DeletePetByIdQueryError = Error;

/**
 * @summary Deletes a specific pet
 */

export function useDeletePetById<
  TData = Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useDeletePetByIdHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useDeletePetByIdQueryOptions(petId, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary health check
 */
export const useHealthCheckHook = () => {
  const healthCheck = useCustomInstance<string>();

  return (version: MaybeRefOrGetter<number> = 1, signal?: AbortSignal) => {
    version = toValue(version);

    return healthCheck({ url: `/v${version}/health`, method: 'GET', signal });
  };
};

export const getHealthCheckQueryKey = (
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'health'] as const;
};

export const useHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
  TError = Error,
>(
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getHealthCheckQueryKey(version);

  const healthCheck = useHealthCheckHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>
  > = ({ signal }) => healthCheck(version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
    TError,
    TData
  >;
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>
>;
export type HealthCheckQueryError = Error;

/**
 * @summary health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
  TError = Error,
>(
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useHealthCheckQueryOptions(version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary combinate nullable and $ref
 */
export const useShowPetWithOwnerHook = () => {
  const showPetWithOwner = useCustomInstance<PetWithTag>();

  return (
    petId: MaybeRefOrGetter<string>,
    version: MaybeRefOrGetter<number> = 1,
    signal?: AbortSignal,
  ) => {
    petId = toValue(petId);
    version = toValue(version);

    return showPetWithOwner({
      url: `/v${version}/pets/${petId}/owner`,
      method: 'GET',
      signal,
    });
  };
};

export const getShowPetWithOwnerQueryKey = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'pets', petId, 'owner'] as const;
};

export const useShowPetWithOwnerQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getShowPetWithOwnerQueryKey(petId, version);

  const showPetWithOwner = useShowPetWithOwnerHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>
  > = ({ signal }) => showPetWithOwner(petId, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () =>
        toValue(version) !== null &&
        toValue(version) !== undefined &&
        toValue(petId) !== null &&
        toValue(petId) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>,
    TError,
    TData
  >;
};

export type ShowPetWithOwnerQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>
>;
export type ShowPetWithOwnerQueryError = Error;

/**
 * @summary combinate nullable and $ref
 */

export function useShowPetWithOwner<
  TData = Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useShowPetWithOwnerHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useShowPetWithOwnerQueryOptions(petId, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
