/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Url-encoded body with `style: deepObject` encoding
 * OpenAPI spec version: 1.0.0
 */
import type { PostAccountsBody, PostAccountsNestedBody } from './model';

export type postAccountsResponse200 = {
  data: void;
  status: 200;
};

export type postAccountsResponseSuccess = postAccountsResponse200 & {
  headers: Headers;
};
export type postAccountsResponse = postAccountsResponseSuccess;

export const getPostAccountsUrl = () => {
  return `/accounts`;
};

export const postAccounts = async (
  postAccountsBody?: PostAccountsBody,
  options?: RequestInit,
): Promise<postAccountsResponse> => {
  const formUrlEncoded = new URLSearchParams();
  if (postAccountsBody?.metadata !== undefined) {
    if (postAccountsBody.metadata?.order_id !== undefined) {
      formUrlEncoded.append(
        `metadata[order_id]`,
        postAccountsBody.metadata.order_id,
      );
    }
  }

  const res = await fetch(getPostAccountsUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAccountsResponse['data'] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAccountsResponse;
};

export type postAccountsNestedResponse200 = {
  data: void;
  status: 200;
};

export type postAccountsNestedResponseSuccess =
  postAccountsNestedResponse200 & {
    headers: Headers;
  };
export type postAccountsNestedResponse = postAccountsNestedResponseSuccess;

export const getPostAccountsNestedUrl = () => {
  return `/accounts/nested`;
};

export const postAccountsNested = async (
  postAccountsNestedBody: PostAccountsNestedBody,
  options?: RequestInit,
): Promise<postAccountsNestedResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, postAccountsNestedBody.name);
  formUrlEncoded.append(
    `metadata[order_id]`,
    postAccountsNestedBody.metadata.order_id,
  );
  if (postAccountsNestedBody.metadata.priority !== undefined) {
    formUrlEncoded.append(
      `metadata[priority]`,
      postAccountsNestedBody.metadata.priority.toString(),
    );
  }
  if (postAccountsNestedBody.metadata.tags !== undefined) {
    postAccountsNestedBody.metadata.tags.forEach((value, index1) =>
      formUrlEncoded.append(`metadata[tags][${index1}]`, value),
    );
  }
  if (postAccountsNestedBody.metadata.shipping !== undefined) {
    if (postAccountsNestedBody.metadata.shipping.city !== undefined) {
      formUrlEncoded.append(
        `metadata[shipping][city]`,
        postAccountsNestedBody.metadata.shipping.city,
      );
    }
    if (postAccountsNestedBody.metadata.shipping.express !== undefined) {
      formUrlEncoded.append(
        `metadata[shipping][express]`,
        postAccountsNestedBody.metadata.shipping.express.toString(),
      );
    }
  }
  if (postAccountsNestedBody.metadata.lines !== undefined) {
    postAccountsNestedBody.metadata.lines.forEach((value, index1) => {
      if (value.sku !== undefined) {
        formUrlEncoded.append(`metadata[lines][${index1}][sku]`, value.sku);
      }
      if (value.quantity !== undefined) {
        formUrlEncoded.append(
          `metadata[lines][${index1}][quantity]`,
          value.quantity.toString(),
        );
      }
    });
  }
  if (
    postAccountsNestedBody.metadata.note !== undefined &&
    postAccountsNestedBody.metadata.note !== null
  ) {
    formUrlEncoded.append(
      `metadata[note]`,
      postAccountsNestedBody.metadata.note,
    );
  }
  if (
    postAccountsNestedBody.metadata.retries !== undefined &&
    postAccountsNestedBody.metadata.retries !== null
  ) {
    formUrlEncoded.append(
      `metadata[retries]`,
      postAccountsNestedBody.metadata.retries.toString(),
    );
  }
  if (postAccountsNestedBody.metadata.matrix !== undefined) {
    postAccountsNestedBody.metadata.matrix.forEach((value, index1) =>
      formUrlEncoded.append(
        `metadata[matrix][${index1}]`,
        JSON.stringify(value),
      ),
    );
  }
  if (postAccountsNestedBody.attributes !== undefined) {
    Object.entries(postAccountsNestedBody.attributes ?? {}).forEach(
      ([key, entryValue]) => {
        if (entryValue !== undefined && entryValue !== null) {
          formUrlEncoded.append(`attributes[${key}]`, entryValue);
        }
      },
    );
  }
  if (postAccountsNestedBody.labels !== undefined) {
    Object.entries(postAccountsNestedBody.labels ?? {}).forEach(
      ([key, entryValue]) => {
        if (entryValue !== undefined && entryValue !== null) {
          entryValue.forEach((value, index1) =>
            formUrlEncoded.append(`labels[${key}][${index1}]`, value),
          );
        }
      },
    );
  }
  if (postAccountsNestedBody.warehouses !== undefined) {
    Object.entries(postAccountsNestedBody.warehouses ?? {}).forEach(
      ([key, entryValue]) => {
        if (entryValue !== undefined && entryValue !== null) {
          if (entryValue.city !== undefined) {
            formUrlEncoded.append(`warehouses[${key}][city]`, entryValue.city);
          }
          if (entryValue.capacity !== undefined) {
            formUrlEncoded.append(
              `warehouses[${key}][capacity]`,
              entryValue.capacity.toString(),
            );
          }
        }
      },
    );
  }
  if (postAccountsNestedBody.freeform !== undefined) {
    Object.entries(postAccountsNestedBody.freeform ?? {}).forEach(
      ([key, value]) => {
        if (value !== undefined && value !== null) {
          if (Array.isArray(value)) {
            value.forEach((v, i) => {
              formUrlEncoded.append(
                `freeform[${key}][${i}]`,
                typeof v === 'object' ? JSON.stringify(v) : String(v),
              );
            });
          } else if (typeof value === 'object') {
            formUrlEncoded.append(`freeform[${key}]`, JSON.stringify(value));
          } else {
            formUrlEncoded.append(`freeform[${key}]`, String(value));
          }
        }
      },
    );
  }
  if (postAccountsNestedBody.codes !== undefined) {
    postAccountsNestedBody.codes.forEach((value) =>
      formUrlEncoded.append(`codes`, value),
    );
  }
  if (postAccountsNestedBody.untouched !== undefined) {
    formUrlEncoded.append(
      `untouched`,
      JSON.stringify(postAccountsNestedBody.untouched),
    );
  }

  const res = await fetch(getPostAccountsNestedUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAccountsNestedResponse['data'] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAccountsNestedResponse;
};
