/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * const-with-enum
 * A property that carries both `enum` and `const` (as FastAPI / Pydantic v2
 * emit for a `Literal[...]` field) must generate the single const literal and
 * must not crash `getTypeConstEnum` with a non-string value.
 * OpenAPI spec version: 1.0.0
 */

export interface Thing {
  name: string;
  int: 1;
  num: 1.5;
  str: 'a';
  bool: true;
}
