/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Fragmentless External Ref
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export type GetPet200 = {
  id: string;
  name?: string;
};

export const getPet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetPet200>> => {
  return axios.get(`/pet`, options);
};

export type GetPetResult = AxiosResponse<GetPet200>;
