/**
 * Generated by orval 🍺
 * Do not edit manually.
 * parameter-ref-schema-ref
 * OpenAPI spec version: 1.0
 */
import type { FilterParameter } from './filterParameter';

export type GetReferencedParamParams = {
  filter?: FilterParameter;
};
