/**
 * Generated by orval 🍺
 * Do not edit manually.
 * parameter-ref-schema-ref
 * OpenAPI spec version: 1.0
 */

export type Kind = (typeof Kind)[keyof typeof Kind];

export const Kind = {
  alpha: 'alpha',
  beta: 'beta',
  gamma: 'gamma',
} as const;
